// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD535NtHvH4D5wx7vjEnT3e94hsYj_6XFY',
    appId: '1:930389726649:web:66d9420c1ffb48481ed268',
    messagingSenderId: '930389726649',
    projectId: 'foxtrot-3bdba',
    authDomain: 'foxtrot-3bdba.firebaseapp.com',
    storageBucket: 'foxtrot-3bdba.firebasestorage.app',
    measurementId: 'G-CHVYECYLY7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC5jEW30FBK0ySlh6Bb1sbIZBUlbQvL5Mo',
    appId: '1:930389726649:android:68de4074aad1ffb41ed268',
    messagingSenderId: '930389726649',
    projectId: 'foxtrot-3bdba',
    storageBucket: 'foxtrot-3bdba.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAuiMYiU4exLCF3R7MRCRh34lL6qvCbcyc',
    appId: '1:930389726649:ios:a34763feb246700f1ed268',
    messagingSenderId: '930389726649',
    projectId: 'foxtrot-3bdba',
    storageBucket: 'foxtrot-3bdba.firebasestorage.app',
    iosClientId:
        '930389726649-t2c3uhi40kafbkbsh2228bcqo9s8hkue.apps.googleusercontent.com',
    iosBundleId: 'com.ethanscafe.cafeApp',
  );
}
